main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('book_list', views.book_list, name='book_list'),
    path('rel', views.rel, name='rel'),
]

quick_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('main/', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models

class Book(models.Model):
    isbn = models.CharField(
        verbose_name='ISBNコード',
        max_length=20
    )
    title = models.CharField(
        verbose_name='署名',
        max_length=100
    )
    price = models.IntegerField(
        verbose_name='価格',
        default=0
    )
    publisher = models.CharField(
        verbose_name='出版社',
        max_length=50,
        choices = {
            ('翔泳社', '翔泳社'),
            ('技術評論社', '技術評論社'),
            ('秀和システム', '秀和システム'),
            ('SBクリエイティブ', 'SBクリエイティブ'),
            ('日経BP', '日経BP'),
        }
    )
    published = models.DateField(
        verbose_name='刊行日'
    )
    def __str__(self):
        return f'{self.title}({self.publisher}/{self.price}円)'

class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    name = models.CharField(
        verbose_name='名前',
        max_length= 20
    )
    body = models.TextField(
        verbose_name='本文',
        max_length=255
    )
    def __str__(self):
        return f'{self.name}: {self.body[:10]}'

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Book

def index(request):
    return HttpResponse('Hello World!')

def book_list(request):
    # books = Book.objects.all()
    books = Book.objects.filter(publisher='翔泳社')
    return render(request, 'main/book_list.html', {
        'books': books
    })

def rel(request):
    return render(request, 'main/rel.html', {
        'book': Book.objects.get(pk=1)
    })

main/templates/main/book_list.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <table>
    <tr>
      <th>ISBNコード</th>
      <th>署名</th>
      <th>価格</th>
      <th>出版社</th>
      <th>刊行日</th>
    </tr>
    {% for b in books %}
    <tr>
      <td>{{ b.isbn }}</td>
      <td>{{ b.title }}</td>
      <td>{{ b.price }}</td>
      <td>{{ b.publisher }}</td>
      <td>{{ b.published | date:'DATE_FORMAT' }}</td>
    </tr>
    {% endfor %}
  </table>
</body>
</html>

main/templates/main/rel.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>{{book.title}}</h1>
  <ul>
  {% for rev in book.review_set.all %}
    <li>{{ rev.body }} （{{ rev.name }}）</li>
  {% endfor %}
  </ul>
</body>
</html>